title: Yoan Chabot
url: "http://yoanchabot.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: "Powered by Jekyll and \"researcher\" by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Research"
   link: "research"
 - name: "Publications"
   link: "publications" 
 - name: "Teaching"
   link: "teaching"
 - name: "Others"
   link: "others"    
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"